flanguage: node_js
node_js:
- '8'
dist: trusty
sudo: required
before_script:
- npm install
- npm install -g bower
- bower install
# script:
# # - npm test
# - npm run build
cache:
  directories:
  - node_modules
env:
  global:
    - CXX=g++-4.8 CC=gcc-4.8
addons:
  - apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_deploy:
- grunt build
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    fqdn: portfolio.bbody.io
    on:
      branch: master
  # - provider: s3
  #   access_key_id: "YOUR AWS ACCESS KEY"
  #   secret_access_key: "YOUR AWS SECRET KEY"
  #   bucket: "S3 Bucket"
  #   skip_cleanup: true
  #   acl: public_read
  #   local_dir: app/responses